<a href="https://colab.research.google.com/github/badineniharshith/AIML-Course/blob/main/AIML_DAY_26_ORDINAL_ENCODING.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

SOURCE :https://www.youtube.com/watch?v=ZftI2fEz0Fw&list=PLKnIA16_Rmvbr7zKYQuBfsVkjoLcJgxHH

In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv('customer.csv')

In [3]:
df.sample(5)

    age  gender   review education purchased
7    60  Female     Poor    School       Yes
1    68  Female     Poor        UG        No
14   15    Male     Poor        PG       Yes
15   75    Male     Poor        UG        No
5    31  Female  Average    School       Yes

In [4]:
df = df.iloc[:,2:]

In [5]:
df.head()

    review education purchased
0  Average    School        No
1     Poor        UG        No
2     Good        PG        No
3     Good        PG        No
4  Average        UG        No

In [6]:
from sklearn.preprocessing import OrdinalEncoder

In [11]:
oe = OrdinalEncoder(categories=[['Poor','Average','Good'],['School','UG','PG']])

In [18]:
from sklearn.preprocessing import LabelEncoder

In [19]:
le = LabelEncoder()